// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: proto/cuttlefish.proto

package cuttlefish

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tentacle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude uint32 `protobuf:"varint,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  uint32 `protobuf:"varint,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Sequence  uint32 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Connected bool   `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`
}

func (x *Tentacle) Reset() {
	*x = Tentacle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cuttlefish_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tentacle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tentacle) ProtoMessage() {}

func (x *Tentacle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cuttlefish_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tentacle.ProtoReflect.Descriptor instead.
func (*Tentacle) Descriptor() ([]byte, []int) {
	return file_proto_cuttlefish_proto_rawDescGZIP(), []int{0}
}

func (x *Tentacle) GetLongitude() uint32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Tentacle) GetLatitude() uint32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Tentacle) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Tentacle) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type GetTentacleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTentacleReq) Reset() {
	*x = GetTentacleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cuttlefish_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTentacleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTentacleReq) ProtoMessage() {}

func (x *GetTentacleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cuttlefish_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTentacleReq.ProtoReflect.Descriptor instead.
func (*GetTentacleReq) Descriptor() ([]byte, []int) {
	return file_proto_cuttlefish_proto_rawDescGZIP(), []int{1}
}

func (x *GetTentacleReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTentacleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tentacle []*Tentacle `protobuf:"bytes,1,rep,name=tentacle,proto3" json:"tentacle,omitempty"`
}

func (x *GetTentacleResp) Reset() {
	*x = GetTentacleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cuttlefish_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTentacleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTentacleResp) ProtoMessage() {}

func (x *GetTentacleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cuttlefish_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTentacleResp.ProtoReflect.Descriptor instead.
func (*GetTentacleResp) Descriptor() ([]byte, []int) {
	return file_proto_cuttlefish_proto_rawDescGZIP(), []int{2}
}

func (x *GetTentacleResp) GetTentacle() []*Tentacle {
	if x != nil {
		return x.Tentacle
	}
	return nil
}

type SetTentacleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tentacle []*Tentacle `protobuf:"bytes,2,rep,name=tentacle,proto3" json:"tentacle,omitempty"`
}

func (x *SetTentacleReq) Reset() {
	*x = SetTentacleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cuttlefish_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTentacleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTentacleReq) ProtoMessage() {}

func (x *SetTentacleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cuttlefish_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTentacleReq.ProtoReflect.Descriptor instead.
func (*SetTentacleReq) Descriptor() ([]byte, []int) {
	return file_proto_cuttlefish_proto_rawDescGZIP(), []int{3}
}

func (x *SetTentacleReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetTentacleReq) GetTentacle() []*Tentacle {
	if x != nil {
		return x.Tentacle
	}
	return nil
}

type SetTentacleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetTentacleResp) Reset() {
	*x = SetTentacleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cuttlefish_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTentacleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTentacleResp) ProtoMessage() {}

func (x *SetTentacleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cuttlefish_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTentacleResp.ProtoReflect.Descriptor instead.
func (*SetTentacleResp) Descriptor() ([]byte, []int) {
	return file_proto_cuttlefish_proto_rawDescGZIP(), []int{4}
}

var File_proto_cuttlefish_proto protoreflect.FileDescriptor

var file_proto_cuttlefish_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x75, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69,
	0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x43, 0x75, 0x74, 0x74, 0x6c, 0x65,
	0x66, 0x69, 0x73, 0x68, 0x22, 0x7e, 0x0a, 0x08, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6e, 0x74, 0x61,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6e,
	0x74, 0x61, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x08, 0x74, 0x65, 0x6e,
	0x74, 0x61, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x75,
	0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x73, 0x68, 0x2e, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c,
	0x65, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x22, 0x52, 0x0a, 0x0e, 0x53,
	0x65, 0x74, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a,
	0x08, 0x74, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x43, 0x75, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x73, 0x68, 0x2e, 0x54, 0x65, 0x6e,
	0x74, 0x61, 0x63, 0x6c, 0x65, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x22,
	0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x32, 0xa0, 0x01, 0x0a, 0x0a, 0x63, 0x75, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x73,
	0x68, 0x12, 0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65,
	0x12, 0x1a, 0x2e, 0x43, 0x75, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x73, 0x68, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x43,
	0x75, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x73, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6e,
	0x74, 0x61, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x53,
	0x65, 0x74, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x43, 0x75, 0x74,
	0x74, 0x6c, 0x65, 0x66, 0x69, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x65, 0x6e, 0x74, 0x61,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x43, 0x75, 0x74, 0x74, 0x6c, 0x65, 0x66,
	0x69, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x73, 0x74, 0x6c, 0x61, 0x73, 0x63, 0x6f, 0x72, 0x70, 0x69,
	0x6f, 0x6e, 0x2f, 0x43, 0x75, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x73, 0x68, 0x3b, 0x63, 0x75,
	0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_cuttlefish_proto_rawDescOnce sync.Once
	file_proto_cuttlefish_proto_rawDescData = file_proto_cuttlefish_proto_rawDesc
)

func file_proto_cuttlefish_proto_rawDescGZIP() []byte {
	file_proto_cuttlefish_proto_rawDescOnce.Do(func() {
		file_proto_cuttlefish_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cuttlefish_proto_rawDescData)
	})
	return file_proto_cuttlefish_proto_rawDescData
}

var file_proto_cuttlefish_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_cuttlefish_proto_goTypes = []interface{}{
	(*Tentacle)(nil),        // 0: Cuttlefish.Tentacle
	(*GetTentacleReq)(nil),  // 1: Cuttlefish.GetTentacleReq
	(*GetTentacleResp)(nil), // 2: Cuttlefish.GetTentacleResp
	(*SetTentacleReq)(nil),  // 3: Cuttlefish.SetTentacleReq
	(*SetTentacleResp)(nil), // 4: Cuttlefish.SetTentacleResp
}
var file_proto_cuttlefish_proto_depIdxs = []int32{
	0, // 0: Cuttlefish.GetTentacleResp.tentacle:type_name -> Cuttlefish.Tentacle
	0, // 1: Cuttlefish.SetTentacleReq.tentacle:type_name -> Cuttlefish.Tentacle
	1, // 2: Cuttlefish.cuttlefish.GetTentacle:input_type -> Cuttlefish.GetTentacleReq
	3, // 3: Cuttlefish.cuttlefish.SetTentacle:input_type -> Cuttlefish.SetTentacleReq
	2, // 4: Cuttlefish.cuttlefish.GetTentacle:output_type -> Cuttlefish.GetTentacleResp
	4, // 5: Cuttlefish.cuttlefish.SetTentacle:output_type -> Cuttlefish.SetTentacleResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cuttlefish_proto_init() }
func file_proto_cuttlefish_proto_init() {
	if File_proto_cuttlefish_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_cuttlefish_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tentacle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cuttlefish_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTentacleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cuttlefish_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTentacleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cuttlefish_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTentacleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cuttlefish_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTentacleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cuttlefish_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cuttlefish_proto_goTypes,
		DependencyIndexes: file_proto_cuttlefish_proto_depIdxs,
		MessageInfos:      file_proto_cuttlefish_proto_msgTypes,
	}.Build()
	File_proto_cuttlefish_proto = out.File
	file_proto_cuttlefish_proto_rawDesc = nil
	file_proto_cuttlefish_proto_goTypes = nil
	file_proto_cuttlefish_proto_depIdxs = nil
}
